/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author quiri
 */
public class MenuInicio extends javax.swing.JFrame {

  /**
   * Creates new form MenuInicio
   */
  public MenuInicio() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButtonSalir = new javax.swing.JButton();
    jButtonNuevaPartida = new javax.swing.JButton();
    jButtonEstadisticas = new javax.swing.JButton();
    jLabelTextBingo = new javax.swing.JLabel();
    jButtonRegistrarJugador = new javax.swing.JButton();
    jLabelFondo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButtonSalir.setBackground(new java.awt.Color(255, 0, 0));
    jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
    jButtonSalir.setText("Salir");
    jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonSalirActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

    jButtonNuevaPartida.setBackground(new java.awt.Color(51, 153, 255));
    jButtonNuevaPartida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonNuevaPartida.setForeground(new java.awt.Color(255, 255, 255));
    jButtonNuevaPartida.setText("Nueva Partida");
    jButtonNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonNuevaPartidaActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonNuevaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 160, 40));

    jButtonEstadisticas.setBackground(new java.awt.Color(0, 153, 255));
    jButtonEstadisticas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonEstadisticas.setForeground(new java.awt.Color(255, 255, 255));
    jButtonEstadisticas.setText("Estadísticas");
    getContentPane().add(jButtonEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 160, 40));

    jLabelTextBingo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
    jLabelTextBingo.setForeground(new java.awt.Color(255, 255, 255));
    jLabelTextBingo.setText("Bingo by Heldys & Quiriat");
    getContentPane().add(jLabelTextBingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 150, -1));

    jButtonRegistrarJugador.setBackground(new java.awt.Color(0, 153, 255));
    jButtonRegistrarJugador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonRegistrarJugador.setForeground(new java.awt.Color(255, 255, 255));
    jButtonRegistrarJugador.setText("Registrar Jugador");
    jButtonRegistrarJugador.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonRegistrarJugadorActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonRegistrarJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 160, 40));

    jLabelFondo.setIcon(new javax.swing.ImageIcon ("Imagenes//fondo.jpg"));
    getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 367, 540));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_jButtonSalirActionPerformed

  private void jButtonNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaPartidaActionPerformed
     // Abre la ventana MenuCrearCartones y cierra la actual
    new MenuCrearCartones().setVisible(true);
    this.dispose();  // Cierra la ventana MenuInicio
  }//GEN-LAST:event_jButtonNuevaPartidaActionPerformed

  private void jButtonRegistrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarJugadorActionPerformed
    new MenuRegistrarJugador().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_jButtonRegistrarJugadorActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MenuInicio().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonEstadisticas;
  private javax.swing.JButton jButtonNuevaPartida;
  private javax.swing.JButton jButtonRegistrarJugador;
  private javax.swing.JButton jButtonSalir;
  private javax.swing.JLabel jLabelFondo;
  private javax.swing.JLabel jLabelTextBingo;
  // End of variables declaration//GEN-END:variables
}
