/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.DefaultListModel;
import java.util.List;
import java.io.IOException;

/**
 *
 * @author quiri
 */
public class MenuRegistrarJugador extends javax.swing.JFrame {

  /**
   * Creates new form MenuRegistrarJugador
   */
  public MenuRegistrarJugador() {
    initComponents();
    jTextFieldNombre.setText("Introduzca el nombre");
    jTextFieldNombre.setForeground(java.awt.Color.GRAY);
    jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
      @Override
      public void focusGained(java.awt.event.FocusEvent evt) {
        if (jTextFieldNombre.getText().equals("Introduzca el nombre")) {
          jTextFieldNombre.setText("");
          jTextFieldNombre.setForeground(java.awt.Color.BLACK);
        }
      }

      @Override
      public void focusLost(java.awt.event.FocusEvent evt) {
        if (jTextFieldNombre.getText().isEmpty()) {
          jTextFieldNombre.setForeground(java.awt.Color.GRAY);
          jTextFieldNombre.setText("Introduzca el nombre");
        }
      }
    });
    jTextFieldCedula.setText("Introduzca la cédula");
    jTextFieldCedula.setForeground(java.awt.Color.GRAY);
    jTextFieldCedula.addFocusListener(new java.awt.event.FocusAdapter() {
      @Override
      public void focusGained(java.awt.event.FocusEvent evt) {
        if (jTextFieldCedula.getText().equals("Introduzca la cédula")) {
          jTextFieldCedula.setText("");
          jTextFieldCedula.setForeground(java.awt.Color.BLACK);
        }
      }

      @Override
      public void focusLost(java.awt.event.FocusEvent evt) {
        if (jTextFieldCedula.getText().isEmpty()) {
          jTextFieldCedula.setForeground(java.awt.Color.GRAY);
          jTextFieldCedula.setText("Introduzca la cédula");
        }
      }
    });

    // Placeholder para jTextFieldCorreo
    jTextFieldCorreo.setText("Introduzca el correo");
    jTextFieldCorreo.setForeground(java.awt.Color.GRAY);
    jTextFieldCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
      @Override
      public void focusGained(java.awt.event.FocusEvent evt) {
        if (jTextFieldCorreo.getText().equals("Introduzca el correo")) {
          jTextFieldCorreo.setText("");
          jTextFieldCorreo.setForeground(java.awt.Color.BLACK);
        }
      }

      @Override
      public void focusLost(java.awt.event.FocusEvent evt) {
        if (jTextFieldCorreo.getText().isEmpty()) {
          jTextFieldCorreo.setForeground(java.awt.Color.GRAY);
          jTextFieldCorreo.setText("Introduzca el correo");
        }
      }
    });
    jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonGuardarActionPerformed(evt);
      }
    });
    this.setLocationRelativeTo(null);
    actualizarListaJugadores();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButtonSalir = new javax.swing.JButton();
    jTextFieldNombre = new javax.swing.JTextField();
    jTextFieldCedula = new javax.swing.JTextField();
    jTextFieldCorreo = new javax.swing.JTextField();
    jLabelTextNombre = new javax.swing.JLabel();
    jLabelTextCedula = new javax.swing.JLabel();
    jLabelTextCorreo = new javax.swing.JLabel();
    jButtonGuardar = new javax.swing.JButton();
    jButtonVolver = new javax.swing.JButton();
    jScrollPanelJugadores = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList<>();
    jLabelFondo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButtonSalir.setBackground(new java.awt.Color(255, 0, 0));
    jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
    jButtonSalir.setText("Salir");
    jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonSalirActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

    jTextFieldNombre.setText("Nombre");
    jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldNombreActionPerformed(evt);
      }
    });
    getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 160, 30));

    jTextFieldCedula.setText("Cedula");
    getContentPane().add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 160, 30));

    jTextFieldCorreo.setText("Correo");
    getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 160, 30));

    jLabelTextNombre.setText("Nombre:");
    getContentPane().add(jLabelTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 70, 30));

    jLabelTextCedula.setText("Cedula:");
    getContentPane().add(jLabelTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 70, 30));

    jLabelTextCorreo.setText("Correo");
    getContentPane().add(jLabelTextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 70, 30));

    jButtonGuardar.setBackground(new java.awt.Color(0, 153, 255));
    jButtonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
    jButtonGuardar.setText("Guardar");
    jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonGuardarActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

    jButtonVolver.setBackground(new java.awt.Color(0, 153, 255));
    jButtonVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
    jButtonVolver.setText("Volver");
    jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonVolverActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

    jList1.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPanelJugadores.setViewportView(jList1);

    getContentPane().add(jScrollPanelJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 490, 130));

    jLabelFondo.setIcon(new javax.swing.ImageIcon("Imagenes\\fondo.jpg"));
    getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 408));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_jButtonSalirActionPerformed

  private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldNombreActionPerformed

  private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
    String nombre = jTextFieldNombre.getText().trim();
    String cedulaString = jTextFieldCedula.getText().trim();
    String correo = jTextFieldCorreo.getText().trim();

    // Validar que no sean los placeholders
    if (!nombre.equals("Introduzca el nombre") && !cedulaString.equals("Introduzca la cédula") && !correo.equals("Introduzca el correo")) {
      try {
        int cedula = Integer.parseInt(cedulaString);
        LogicaDeBingo.Jugador jugador = new LogicaDeBingo.Jugador(nombre, cedula, correo);

        // Guardar en CSV
        jugador.guardar();

        javax.swing.JOptionPane.showMessageDialog(this, "Jugador guardado exitosamente!");

      } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Introduzca una cédula válida.");
      } catch (IllegalArgumentException e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
      } catch (IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el jugador: " + e.getMessage());
      }
    } else {
      javax.swing.JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos.");
    }
    
    jTextFieldNombre.setText("Introduzca el nombre");
    jTextFieldNombre.setForeground(java.awt.Color.GRAY);
    jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
      @Override
      public void focusGained(java.awt.event.FocusEvent evt) {
        if (jTextFieldNombre.getText().equals("Introduzca el nombre")) {
          jTextFieldNombre.setText("");
          jTextFieldNombre.setForeground(java.awt.Color.BLACK);
        }
      }

      @Override
      public void focusLost(java.awt.event.FocusEvent evt) {
        if (jTextFieldNombre.getText().isEmpty()) {
          jTextFieldNombre.setForeground(java.awt.Color.GRAY);
          jTextFieldNombre.setText("Introduzca el nombre");
        }
      }
    });
    jTextFieldCedula.setText("Introduzca la cédula");
    jTextFieldCedula.setForeground(java.awt.Color.GRAY);
    jTextFieldCedula.addFocusListener(new java.awt.event.FocusAdapter() {
      @Override
      public void focusGained(java.awt.event.FocusEvent evt) {
        if (jTextFieldCedula.getText().equals("Introduzca la cédula")) {
          jTextFieldCedula.setText("");
          jTextFieldCedula.setForeground(java.awt.Color.BLACK);
        }
      }

      @Override
      public void focusLost(java.awt.event.FocusEvent evt) {
        if (jTextFieldCedula.getText().isEmpty()) {
          jTextFieldCedula.setForeground(java.awt.Color.GRAY);
          jTextFieldCedula.setText("Introduzca la cédula");
        }
      }
    });

    // Placeholder para jTextFieldCorreo
    jTextFieldCorreo.setText("Introduzca el correo");
    jTextFieldCorreo.setForeground(java.awt.Color.GRAY);
    jTextFieldCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
      @Override
      public void focusGained(java.awt.event.FocusEvent evt) {
        if (jTextFieldCorreo.getText().equals("Introduzca el correo")) {
          jTextFieldCorreo.setText("");
          jTextFieldCorreo.setForeground(java.awt.Color.BLACK);
        }
      }

      @Override
      public void focusLost(java.awt.event.FocusEvent evt) {
        if (jTextFieldCorreo.getText().isEmpty()) {
          jTextFieldCorreo.setForeground(java.awt.Color.GRAY);
          jTextFieldCorreo.setText("Introduzca el correo");
        }
      }
    });
    actualizarListaJugadores();
  }//GEN-LAST:event_jButtonGuardarActionPerformed

  private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
    new MenuInicio().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_jButtonVolverActionPerformed

  private void actualizarListaJugadores() {
    try {
      DefaultListModel<String> model = new DefaultListModel<>();
      List<String> jugadores = LogicaDeBingo.Jugador.listarJugadores();

      for (String jugador : jugadores) {
        model.addElement(jugador);
      }

      jList1.setModel(model);
    } catch (IOException e) {
      javax.swing.JOptionPane.showMessageDialog(this, "Error al leer jugadores: " + e.getMessage());
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MenuRegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MenuRegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MenuRegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MenuRegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MenuRegistrarJugador().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonGuardar;
  private javax.swing.JButton jButtonSalir;
  private javax.swing.JButton jButtonVolver;
  private javax.swing.JLabel jLabelFondo;
  private javax.swing.JLabel jLabelTextCedula;
  private javax.swing.JLabel jLabelTextCorreo;
  private javax.swing.JLabel jLabelTextNombre;
  private javax.swing.JList<String> jList1;
  private javax.swing.JScrollPane jScrollPanelJugadores;
  private javax.swing.JTextField jTextFieldCedula;
  private javax.swing.JTextField jTextFieldCorreo;
  private javax.swing.JTextField jTextFieldNombre;
  // End of variables declaration//GEN-END:variables
}
