/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import LogicaDeBingo.Carton;
import java.awt.event.KeyEvent;
import java.awt.Color;
/**
 *
 * @author quiri
 */
public class MenuCrearCartones extends javax.swing.JFrame {

  /**
   * Creates new form MenuCrearCartones
   */
  public MenuCrearCartones() {
    initComponents();
    this.setLocationRelativeTo(null);

    jTextFieldGenerarCartones.setForeground(Color.GRAY);
    
    jTextFieldGenerarCartones.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                evt.consume();
            }
        }
    });
    
    jTextFieldGenerarCartones.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (jTextFieldGenerarCartones.getText().equals("Valor entre 1 y 500")) {
                jTextFieldGenerarCartones.setText("");
                jTextFieldGenerarCartones.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (jTextFieldGenerarCartones.getText().isEmpty()) {
                jTextFieldGenerarCartones.setForeground(Color.GRAY);
                jTextFieldGenerarCartones.setText("Valor entre 1 y 500");
            } else {
                // Verifica si el número ingresado está dentro del rango
                int num;
                try {
                    num = Integer.parseInt(jTextFieldGenerarCartones.getText());
                    if (num < 1 || num > 500) {
                        jTextFieldGenerarCartones.setForeground(Color.RED);
                        jTextFieldGenerarCartones.setText("Valor entre 1 y 500");
                    }
                } catch (NumberFormatException e) {
                    jTextFieldGenerarCartones.setForeground(Color.RED);
                    jTextFieldGenerarCartones.setText("Valor entre 1 y 500");
                }
            }
        }
    });
  }
  private void borrarDirectorioCartones() {
    try {
        File directorio = new File("cartones");
        if (directorio.exists()) {
            Files.walk(directorio.toPath())
                .sorted((o1, o2) -> -o1.compareTo(o2)) // Reverse order to start with deepest entries first
                .map(Path::toFile)
                .forEach(File::delete);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
  }



  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
  private void initComponents() {

    jButtonSalir = new javax.swing.JButton();
    jButtonVolver = new javax.swing.JButton();
    jLabelGenerarCarton = new javax.swing.JLabel();
    jTextFieldGenerarCartones = new javax.swing.JTextField();
    jLabelCantidadCartones = new javax.swing.JLabel();
    jButtonGenerarCartones = new javax.swing.JButton();
    jLabelFondo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButtonSalir.setBackground(new java.awt.Color(255, 51, 51));
    jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
    jButtonSalir.setText("Salir");
    jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonSalirActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

    jButtonVolver.setBackground(new java.awt.Color(0, 153, 255));
    jButtonVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
    jButtonVolver.setText("Volver");
    getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

    jLabelGenerarCarton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabelGenerarCarton.setText("Generar cartones del juego");
    getContentPane().add(jLabelGenerarCarton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 190, 40));

    jTextFieldGenerarCartones.setText("Valor entre 1 y 500");
    getContentPane().add(jTextFieldGenerarCartones, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 120, 40));

    jLabelCantidadCartones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabelCantidadCartones.setText("Cantidad:");
    getContentPane().add(jLabelCantidadCartones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 80, -1));

    jButtonGenerarCartones.setBackground(new java.awt.Color(0, 153, 255));
    jButtonGenerarCartones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonGenerarCartones.setForeground(new java.awt.Color(255, 255, 255));
    jButtonGenerarCartones.setText("Generar");
    jButtonGenerarCartones.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonGenerarCartonesActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonGenerarCartones, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

    jLabelFondo.setIcon(new javax.swing.ImageIcon("Imagenes\\fondo.jpg"));
    getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 410));

    pack();
  }// </editor-fold>                        

  private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {                                             
    System.exit(0);// TODO add your handling code here:
  }                                            

  private void jButtonGenerarCartonesActionPerformed(java.awt.event.ActionEvent evt) {                                                       
    // Borra el directorio existente de cartones
    borrarDirectorioCartones();
    
    try {
        int numCartones = Integer.parseInt(jTextFieldGenerarCartones.getText());
        if(numCartones >= 1 && numCartones <= 500) {
            // Generar cartones
            ArrayList<Carton> cartones = Carton.generarCartones(numCartones);

            // Puedes manejar la lista de cartones generados según lo que necesites hacer con ellos.
            // Por ejemplo, si quisieras imprimir las matrices de los cartones generados, puedes hacerlo así:
            // for(Carton carton : cartones) {
            //     carton.imprimirMatriz();
            // }

            // Por el momento, solo vamos a mostrar un mensaje confirmando la cantidad de cartones generados.
            javax.swing.JOptionPane.showMessageDialog(this, numCartones + " cartones generados exitosamente!");

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor entre 1 y 500.");
          }
    } catch(NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor válido.");
      }
  }                                                      

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MenuCrearCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MenuCrearCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MenuCrearCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MenuCrearCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MenuCrearCartones().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify                     
  private javax.swing.JButton jButtonGenerarCartones;
  private javax.swing.JButton jButtonSalir;
  private javax.swing.JButton jButtonVolver;
  private javax.swing.JLabel jLabelCantidadCartones;
  private javax.swing.JLabel jLabelFondo;
  private javax.swing.JLabel jLabelGenerarCarton;
  private javax.swing.JTextField jTextFieldGenerarCartones;
  // End of variables declaration                   
}
