/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import LogicaDeBingo.Jugador;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import LogicaDeBingo.CuentaCorreo;
import java.io.FileWriter;
import java.io.PrintWriter;


/**
 *
 * @author quiri
 */
public class MenuEnviarCarton extends javax.swing.JFrame {

  private static ArrayList<String> cartonesAsignados = new ArrayList<>();

  /**
   * Creates new form MenuEnviarCarton
   */
  public MenuEnviarCarton() {
    initComponents();
    this.setLocationRelativeTo(null);
    jComboBoxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1", "2", "3", "4", "5"}));
    jTextFieldCedula.setText("ej: 703310994");
    jTextFieldCedula.setForeground(java.awt.Color.GRAY);
    jTextFieldCedula.addFocusListener(new java.awt.event.FocusAdapter() {
      @Override
      public void focusGained(java.awt.event.FocusEvent evt) {
        if (jTextFieldCedula.getText().equals("ej: 703310994")) {
          jTextFieldCedula.setText("");
          jTextFieldCedula.setForeground(java.awt.Color.BLACK);
        }
      }

      @Override
      public void focusLost(java.awt.event.FocusEvent evt) {
        if (jTextFieldCedula.getText().isEmpty()) {
          jTextFieldCedula.setForeground(java.awt.Color.GRAY);
          jTextFieldCedula.setText("ej: 703310994");
        }
      }
    });
    jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        String cedula = jTextFieldCedula.getText().trim();

        if (cedula.isEmpty() || cedula.equals("ej: 703310994")) {
          javax.swing.JOptionPane.showMessageDialog(null, "Por favor, ingrese un número de cédula válido.");
          return;
        }

        String correo = obtenerCorreoPorCedula(cedula);
        if (correo == null) {
          javax.swing.JOptionPane.showMessageDialog(null, "No se encontró un correo asociado a esta cédula.");
          return;
        }

        int cantidadCartones = Integer.parseInt(jComboBoxCantidad.getSelectedItem().toString());
        ArrayList<String> cartonesDisponibles = obtenerCartonesDisponibles();

        if (cartonesDisponibles.size() < cantidadCartones) {
          javax.swing.JOptionPane.showMessageDialog(null, "No hay suficientes cartones disponibles. Por favor, elija una cantidad menor.");
          return;
        }

        ArrayList<String> rutasImagenes = new ArrayList<>();
        for (int i = 0; i < cantidadCartones; i++) {
          String nombreCarton = cartonesDisponibles.get(i);
          rutasImagenes.add("cartones/" + nombreCarton);
          cartonesAsignados.add(nombreCarton.replace(".png", "")); // Asume que los cartones tienen extensión .png
        }

        CuentaCorreo cuenta = new CuentaCorreo("bingoteclimon@gmail.com");
        cuenta.enviarCorreo(correo, "Tus cartones del Bingo", "Aquí están tus cartones:", rutasImagenes);
        guardarCartonesAsignados();
        javax.swing.JOptionPane.showMessageDialog(null, "Cartones enviados con éxito.");
      }
    });

    cargarCartonesAsignados();

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButtonSalir = new javax.swing.JButton();
    jButtonVolver = new javax.swing.JButton();
    jTextFieldCedula = new javax.swing.JTextField();
    jLabelTextCantidad = new javax.swing.JLabel();
    jLabelTextCedula = new javax.swing.JLabel();
    jButtonEnviar = new javax.swing.JButton();
    jComboBoxCantidad = new javax.swing.JComboBox<>();
    jButtonContinuar = new javax.swing.JButton();
    jLabelTextIJugador = new javax.swing.JLabel();
    jLabelFondo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButtonSalir.setBackground(new java.awt.Color(255, 0, 0));
    jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
    jButtonSalir.setText("Salir");
    jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonSalirActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

    jButtonVolver.setBackground(new java.awt.Color(0, 153, 255));
    jButtonVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
    jButtonVolver.setText("Volver");
    jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonVolverActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

    jTextFieldCedula.setText("Cedula");
    getContentPane().add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 110, 30));

    jLabelTextCantidad.setText("Cantidad:");
    getContentPane().add(jLabelTextCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 30));

    jLabelTextCedula.setText("Cedula:");
    getContentPane().add(jLabelTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 80, 30));

    jButtonEnviar.setBackground(new java.awt.Color(0, 153, 255));
    jButtonEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonEnviar.setForeground(new java.awt.Color(255, 255, 255));
    jButtonEnviar.setText("Enviar");
    getContentPane().add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

    jComboBoxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBoxCantidad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBoxCantidadActionPerformed(evt);
      }
    });
    getContentPane().add(jComboBoxCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 100, 30));

    jButtonContinuar.setBackground(new java.awt.Color(0, 153, 255));
    jButtonContinuar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonContinuar.setForeground(new java.awt.Color(255, 255, 255));
    jButtonContinuar.setText("Continuar");
    jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonContinuarActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, 40));

    jLabelTextIJugador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabelTextIJugador.setText("Introduce los jugadores de este partida");
    getContentPane().add(jLabelTextIJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

    jLabelFondo.setIcon(new javax.swing.ImageIcon("Imagenes\\fondo.jpg"));
    getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 408));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_jButtonSalirActionPerformed

  private void jComboBoxCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCantidadActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jComboBoxCantidadActionPerformed

  private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonVolverActionPerformed

  private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
    // Abre la ventana MenuCrearCartones y cierra la actual
    new MenuTipoDeJuego().setVisible(true);
    this.dispose();  // Cierra la ventana MenuInicio
  }//GEN-LAST:event_jButtonContinuarActionPerformed

  private String obtenerCorreoPorCedula(String cedula) {
    String correo = null;
    String linea;
    String rutaCSV = "jugadores.csv"; // Actualiza esto con la ruta correcta a tu archivo CSV

    try (BufferedReader br = new BufferedReader(new FileReader(rutaCSV))) {
      while ((linea = br.readLine()) != null) {
        String[] valores = linea.split(","); // Asume que las columnas están separadas por comas
        if (valores[0].trim().equals(cedula)) { // Si la cédula coincide
          correo = valores[2].trim(); // Asume que el correo está en la segunda columna
          break;
        }
      }
    } catch (IOException e) {
      e.printStackTrace();
    }
    return correo;
  }

  private ArrayList<String> obtenerCartonesDisponibles() {
    File directorioCartones = new File("cartones");
    ArrayList<String> cartonesDisponibles = new ArrayList<>(Arrays.asList(directorioCartones.list()));
    cartonesDisponibles.removeAll(cartonesAsignados);
    return cartonesDisponibles;
  }

  private void cargarCartonesAsignados() {
    String ruta = "cartonesAsignados.txt"; // Ajusta la ruta si es necesario
    try (BufferedReader br = new BufferedReader(new FileReader(ruta))) {
      String linea;
      while ((linea = br.readLine()) != null) {
        cartonesAsignados.add(linea.trim());
      }
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  private void guardarCartonesAsignados() {
    try (PrintWriter out = new PrintWriter(new FileWriter("cartonesAsignados.txt", true))) {
      for (String carton : cartonesAsignados) {
        out.println(carton);
      }
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
  
  public static ArrayList<String> getCartonesAsignados() {
    return cartonesAsignados;
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MenuEnviarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MenuEnviarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MenuEnviarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MenuEnviarCarton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MenuEnviarCarton().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonContinuar;
  private javax.swing.JButton jButtonEnviar;
  private javax.swing.JButton jButtonSalir;
  private javax.swing.JButton jButtonVolver;
  private javax.swing.JComboBox<String> jComboBoxCantidad;
  private javax.swing.JLabel jLabelFondo;
  private javax.swing.JLabel jLabelTextCantidad;
  private javax.swing.JLabel jLabelTextCedula;
  private javax.swing.JLabel jLabelTextIJugador;
  private javax.swing.JTextField jTextFieldCedula;
  // End of variables declaration//GEN-END:variables
}
