/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import LogicaDeBingo.Bola;
import LogicaDeBingo.JuegoEnX;
import LogicaDeBingo.Carton;
import java.util.ArrayList;
import java.util.List;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import java.util.stream.Collectors;

/**
 *
 * @author quiri
 */
public class VentanaJuego extends javax.swing.JFrame {

  private Bola bola = new Bola();
  private ArrayList<Integer> numerosLlamados = new ArrayList<>();

  /**
   * Creates new form VentanaJuego
   */
  public VentanaJuego() {
    initComponents();
    this.setLocationRelativeTo(null);
    jButtonCantarNumero.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        try {
          int numero = bola.generarNumeroAleatorio();
          numerosLlamados.add(numero);
          String numerosStr = String.join(",", numerosLlamados.stream()
                  .map(String::valueOf)
                  .collect(Collectors.toList()));

          jTextField1.setText(insertNewlines(numerosStr, 24));
          boolean hayGanadores = JuegoEnX.buscarGanadores(numerosLlamados, MenuEnviarCarton.getCartonesAsignados());
          ArrayList<String> ganadores = JuegoEnX.getListaCodigosCartonesGanadores();
            if (hayGanadores) {
              // Construye el mensaje una vez con todos los códigos de los cartones ganadores
              String mensaje = "¡Tenemos ganadores en X! Los códigos de los cartones ganadores son:\n";
              mensaje += String.join(", ", ganadores);
              javax.swing.JOptionPane.showMessageDialog(null, mensaje);
            }
        } catch (IllegalStateException e) {
          javax.swing.JOptionPane.showMessageDialog(null, e.getMessage());
        }
      }
    });

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelTextPremio = new javax.swing.JLabel();
    jLabelTextTipoDeJuego = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jButtonCantarNumero = new javax.swing.JButton();
    jLabelNumerosCantados = new javax.swing.JLabel();
    jLabelFondo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabelTextPremio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabelTextPremio.setText("Premio:");
    getContentPane().add(jLabelTextPremio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 180, -1));

    jLabelTextTipoDeJuego.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabelTextTipoDeJuego.setText("Tipo De Juego:");
    getContentPane().add(jLabelTextTipoDeJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

    jTextField1.setText("jTextField1");
    getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 380, 130));

    jButtonCantarNumero.setBackground(new java.awt.Color(0, 153, 255));
    jButtonCantarNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButtonCantarNumero.setForeground(new java.awt.Color(255, 255, 255));
    jButtonCantarNumero.setText("Cantar Numero");
    jButtonCantarNumero.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCantarNumeroActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonCantarNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 140, 50));

    jLabelNumerosCantados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabelNumerosCantados.setText("Numeros Cantados:");
    getContentPane().add(jLabelNumerosCantados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

    jLabelFondo.setIcon(new javax.swing.ImageIcon("Imagenes\\fondo.jpg"));
    getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 408));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonCantarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCantarNumeroActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonCantarNumeroActionPerformed

  private String insertNewlines(String original, int interval) {
    StringBuilder result = new StringBuilder();
    char[] chars = original.toCharArray();

    for (int i = 0; i < chars.length; i++) {
      if (i > 0 && i % interval == 0) {
        result.append("\n");
      }
      result.append(chars[i]);
    }

    return result.toString();
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VentanaJuego().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonCantarNumero;
  private javax.swing.JLabel jLabelFondo;
  private javax.swing.JLabel jLabelNumerosCantados;
  private javax.swing.JLabel jLabelTextPremio;
  private javax.swing.JLabel jLabelTextTipoDeJuego;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
}
